In [8]:
import pandas as pd
import numpy as np

In [94]:
betResults = pd.read_csv('./model/betResults.csv', encoding = 'unicode_escape')

In [95]:
betResults

,Time Script Ran,Game Date,Sport,Team,Bet Amount,Odds of Winning,Potential Winnings,Expected Value,Winner,Bet Winnings,Row_Key
0,11/19/20,11/21/20,CFB,Syracuse,100,0.238757,600,67,No Win,-100,NaN
1,11/19/20,11/21/20,CFB,Air Force,100,0.870559,28,11,Air Force,28,NaN
2,11/19/20,11/21/20,CFB,Appalachian St.,100,0.424750,168,13,No Win,-100,NaN
3,11/19/20,11/21/20,CFB,Texas St.,100,0.434182,172,18,Texas St.,172,NaN
4,11/19/20,11/21/20,CFB,Temple,100,0.565550,142,36,No Win,-100,NaN
...,...,...,...,...,...,...,...,...,...,...,...
329,12/9/20 21:09,12/10/20,CBB,Northern Arizona,100,0.310000,295,22,No Win,-100,12/10/20_CBB_Northern Arizona
330,12/10/20 9:24,12/10/20,CBB,New Orleans,100,0.370000,215,16,No Win,-100,12/10/20_CBB_New Orleans
331,12/10/20 9:24,12/10/20,CBB,North Dakota,100,0.450000,152,13,North Dakota,152,12/10/20_CBB_North Dakota
332,12/9/20 21:09,12/10/20,CBB,Long Beach St.,100,0.090000,1300,25,No Win,-100,12/10/20_CBB_Long Beach St.
333,12/9/20 22:31,12/10/20,NFL,NE,100,0.355085,210,10,No Win,-100,12/10/20_NFL_NE

In [96]:
betResults['Money'] = 1
for i in range(len(betResults)):
    if betResults['Winner'][i] == 'No Win':
        betResults['Money'][i] = 0
    else:
        betResults['Money'][i] = 1
        
betResults

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time Script Ran,Game Date,Sport,Team,Bet Amount,Odds of Winning,Potential Winnings,Expected Value,Winner,Bet Winnings,Row_Key,Money
0,11/19/20,11/21/20,CFB,Syracuse,100,0.238757,600,67,No Win,-100,NaN,0
1,11/19/20,11/21/20,CFB,Air Force,100,0.870559,28,11,Air Force,28,NaN,1
2,11/19/20,11/21/20,CFB,Appalachian St.,100,0.424750,168,13,No Win,-100,NaN,0
3,11/19/20,11/21/20,CFB,Texas St.,100,0.434182,172,18,Texas St.,172,NaN,1
4,11/19/20,11/21/20,CFB,Temple,100,0.565550,142,36,No Win,-100,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
329,12/9/20 21:09,12/10/20,CBB,Northern Arizona,100,0.310000,295,22,No Win,-100,12/10/20_CBB_Northern Arizona,0
330,12/10/20 9:24,12/10/20,CBB,New Orleans,100,0.370000,215,16,No Win,-100,12/10/20_CBB_New Orleans,0
331,12/10/20 9:24,12/10/20,CBB,North Dakota,100,0.450000,152,13,North Dakota,152,12/10/20_CBB_North Dakota,1
332,12/9/20 21:09,12/10/20,CBB,Long Beach St.,100,0.090000,1300,25,No Win,-100,12/10/20_CBB_Long Beach St.,0
333,12/9/20 22:31,12/10/20,NFL,NE,100,0.355085,210,10,No Win,-100,12/10/20_NFL_NE,0

In [97]:
betResults = betResults.drop(columns=['Time Script Ran', 'Game Date', 'Sport', 'Team', 'Bet Amount', 'Expected Value', 'Row_Key', 'Bet Winnings', 'Winner'])

betResults

     Odds of Winning  Potential Winnings  Money
0           0.238757                 600      0
1           0.870559                  28      1
2           0.424750                 168      0
3           0.434182                 172      1
4           0.565550                 142      0
..               ...                 ...    ...
329         0.310000                 295      0
330         0.370000                 215      0
331         0.450000                 152      1
332         0.090000                1300      0
333         0.355085                 210      0

[334 rows x 3 columns]

In [19]:
def odds_loss(y_true, y_pred):
    """
    The function implements the custom loss function
    
    Inputs
    true : a vector of dimension batch_size, 7. A label encoded version of the output and the backp1_a and backp1_b
    pred : a vector of probabilities of dimension batch_size , 5.
    
    Returns 
    the loss value
    """
    win = y_true[6]
    odds = y_true[5]
    gain_loss_vector = K.concatenate([win * (odds) + (-100*(1-odds)),
      K.zeros_like(odds)], axis=1)
    return -1 * K.mean(K.sum(gain_loss_vector * y_pred, axis=1))

In [98]:
def get_data():
    X = betResults.values[:, 5:-5]
    y = betResults['Money']
    y_full = np.zeros((X.shape[0], 8))
    for i, y_i in enumerate(y):
        if y_i == 1:
            y_full[i, 0] = 1.0
            y_full[i, 1] = 1.0
        if y_i == 2:
            y_full[i, 2] = 1.0
            y_full[i, 3] = 1.0
        if y_i == 3:
            y_full[i, 1] = 1.0
            y_full[i, 3] = 1.0
            y_full[i, 4] = 1.0
        y_full[i, 6] = X[i, 1] # ADD ODDS OF HOME TEAM
        y_full[i, 7] = X[i, 2] # ADD ODDS OF AWAY TEAM
    return X, y_full, y
X, y, outcome = get_data()
# SPLIT THE DATA IN TRAIN AND TEST DATASET.
train_x, test_x, train_y, test_y, = train_test_split(X,  y)

IndexError: index 1 is out of bounds for axis 1 with size 0

In [99]:

import random
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn import datasets
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel


#create lists for x and y values for training and testing data for differnt machine learning algorithms
results_mlp_train = []
results_mlp_test=[]
X_Axis=[]




results_tree_train = []
results_tree_test=[]




results_mlp_train_feature = []
results_mlp_test_feature=[]


#specify different ML algorithms
clf_mlp = MLPClassifier(activation="logistic", solver="adam", alpha=1e-5, hidden_layer_sizes=(15,10), random_state=1,max_iter=1000,learning_rate_init=.1,verbose=False)
clf_tree = DecisionTreeClassifier(criterion = 'entropy', random_state=0, max_depth=3)
clf = ExtraTreesClassifier(n_estimators=50)

#Create AUC for different datasets and ml algorithms
def edges_index(dataset, y1, y2, mlAlgo):
    frac=.1
    clf_mlp = MLPClassifier(activation="logistic", solver="adam", alpha=1e-5, hidden_layer_sizes=(15,10), random_state=1,max_iter=1000,learning_rate_init=.1,verbose=False)
    clf_tree = DecisionTreeClassifier(criterion = 'entropy', random_state=0, max_depth=3)
    
    for i in range(9):
        new_dataset = dataset.sample(n=round(frac*len(dataset)), random_state=1)
        X = betResults.iloc[:, :-2]
        y = betResults['Money']
        
        

        
#         if len(dataset.columns) == len(betResults.columns):
#             X = new_dataset.iloc[:, : 28]
#         else:
#             X = new_dataset.iloc[:,:-1]



        X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9,test_size=0.1, random_state=1)

        mlAlgo = mlAlgo.fit(X_train, y_train)
        y_pred =  mlAlgo.predict(X_test)
        y1.append(accuracy_score(y_true=y_train, y_pred=mlAlgo.predict(X_train)))
        y2.append(accuracy_score(y_true=y_test, y_pred=y_pred))
        if len(X_Axis)<3:
            X_Axis.append("{:.0%}".format(round(frac,2)))
        frac = frac+.1
        
        

edges_index(betResults, results_mlp_train, results_mlp_test, clf_mlp)
edges_index(betResults, results_tree_train, results_tree_test, clf_tree)

print(results_mlp_train)
print(results_mlp_test)

[0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74]
[0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765, 0.7058823529411765]

In [62]:
# import all the required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# split into input and output variables
X = betResults.iloc[:, :-1]
y = betResults.iloc[:,-1]

# moving forward assuming no mising values in dataset

# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

# instantiate the OrdinalEncoder class to encode categorical input features
oe = OrdinalEncoder()
# fit the OrdinalEncoder class on training set
oe.fit(X_train)
# transform training and test sets and convert to DFs
X_train_enc = pd.DataFrame(oe.transform(X_train), columns=X_train.columns)
X_test_enc = pd.DataFrame(oe.transform(X_test), columns=X_test.columns)

# instantiate the LabelEncoder class to encode the categorical target class
le = LabelEncoder()
# fit the LabelEncoder class on training set
le.fit(y_train)
# transform training and test target variables and convert to DFs
y_train_enc = pd.DataFrame(le.transform(y_train))
y_test_enc = pd.DataFrame(le.transform(y_test))

# instantiate SelectKBest class to select the best 4 features
# use score_func=mutual_info_classif for Mutual Information
# Use k='all' to see the scores for all features
fs = SelectKBest(score_func=chi2, k=4)
# fit on training features and target
fs.fit(X_train_enc, y_train_enc)
# transform training and test features and convert to DFs. These will be fed to the ML algorithm for model training
X_train_fs = pd.DataFrame(fs.transform(X_train_enc), columns = X_train_enc.columns[fs.get_support()])
X_test_fs = pd.DataFrame(fs.transform(X_test_enc), columns = X_test_enc.columns[fs.get_support()])

# define classification algorithm
model = LogisticRegression()
# fit the model
model.fit(X_train_fs, y_train_enc)
# predict
yhat = model.predict(X_test_fs)
# evaluate predictions
accuracy = accuracy_score(y_test_enc, yhat)
print('Accuracy: %.2f' % (accuracy*100))

ValueError: Found unknown categories [33, 116, 148, 334, 355, 423, 425, 560, 800] in column 0 during transform